[package]
name = "boxion"
version = "0.1.1"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion="*"
